
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javafx.scene.AccessibleRole;

import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Speed
 */
public class ConfirmPasswordforDelete extends javax.swing.JFrame {

   
    public static ConfirmPasswordforDelete Instance;
    /**
     * Creates new form AdeBankingDriver
     */
    public ConfirmPasswordforDelete() {

        initComponents();
        Instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        iconprofile = new javax.swing.JLabel();
        lblcustomerlogin = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        btnconfirm = new javax.swing.JButton();
        lblexit = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        viewpass = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        iconprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        lblcustomerlogin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblcustomerlogin.setForeground(new java.awt.Color(255, 255, 255));
        lblcustomerlogin.setText("CONFIRM PASSWORD");

        lblpass.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblpass.setForeground(new java.awt.Color(255, 255, 255));
        lblpass.setText("Password:");

        btnconfirm.setBackground(new java.awt.Color(2, 94, 144));
        btnconfirm.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirm.setText("CONFIRM");
        btnconfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconfirmMouseEntered(evt);
            }
        });
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
              
            }
        });

        lblexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exiticon.png"))); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        jpfPassword.setBackground(new java.awt.Color(0, 153, 204));
        jpfPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpfPassword.setBorder(null);
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        viewpass.setBackground(new java.awt.Color(0, 153, 204));
        viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        viewpass.setSelected(true);
        viewpass.setBorder(null);
        viewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 168, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpass)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewpass)))
                .addGap(0, 128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(iconprofile)
                        .addGap(204, 204, 204)
                        .addComponent(lblexit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblcustomerlogin)
                        .addGap(170, 170, 170))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblexit)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(iconprofile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblcustomerlogin)
                .addGap(18, 18, 18)
                .addComponent(lblpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  // <editor-fold defaultstate="collapsed" desc="Generated Code">                          


    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        this.dispose();
        lblexit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblexitMouseClicked

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed

    }//GEN-LAST:event_jpfPasswordActionPerformed

    private void viewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpassActionPerformed
        if (viewpass.isSelected()) {
            jpfPassword.setEchoChar('*');
            viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png")));
        } else {
            jpfPassword.setEchoChar((char) 0);
            viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png")));
        }
    }//GEN-LAST:event_viewpassActionPerformed

    private void btnconfirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseEntered
        btnconfirm.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));


    }//GEN-LAST:event_btnconfirmMouseEntered

    private void btnconfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmMouseClicked
 
        customerpassconfirm = jpfPassword.getText();
        String passPassword = ConfirmDetailsforDetails.Instance.getPass();
        String tempaccnum = ConfirmDetailsforDetails.Instance.getAccountNumber();
        double tempbalance = 0.00;
        double checktempbalance;
        
AccountTransactions foundAccount = AccountTransactions.findAccount(tempaccnum);
checktempbalance = foundAccount.getCustomerBalance();
if (customerpassconfirm.equals(passPassword)){

     
  
     foundAccount.setcustomerBalance(0);
     String num = foundAccount.getCustomerAccount();
    
     Customer foundCustomerAccountNum = Customer.findCustomerAccountNum(num);
     
     
     foundCustomerAccountNum.setaccountNum("Account Deleted");
     foundCustomerAccountNum.setcustomerDOB("Account Deleted");
     foundCustomerAccountNum.setcustomerFirst("Account Deleted");
     foundCustomerAccountNum.setcustomerFirst("Account Deleted");
     foundCustomerAccountNum.setcustomerID("Account Deleted");
     foundCustomerAccountNum.setcustomerLast("Account Deleted");
      foundCustomerAccountNum.setcustomerPPSN("Account Deleted");
       foundCustomerAccountNum.setcustomerPass("Account Deleted");
       
       AdeBank.Instance.getLblbalance().setEnabled(false);
    	 AdeBank.Instance.getLblwithdraw().setEnabled(false);
    	 AdeBank.Instance.getLblviewdetails().setEnabled(false);
    	 AdeBank.Instance.getLbllogout().setEnabled(false);
         AdeBank.Instance.getLbllodgement().setEnabled(false);
         AdeBank.Instance.getLbllogin().setEnabled(false);
    	 AdeBank.Instance.getLblcreate().setEnabled(true);
         this.dispose();
         
     
     
     
     
}   else {
      new ErrorPasswordDelete().setVisible(true);
     jpfPassword.setText("");
     
     }
    }//GEN-LAST:event_btnconfirmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new ConfirmPasswordforDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirm;
    private javax.swing.JLabel iconprofile;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JLabel lblcustomerlogin;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblpass;
    private javax.swing.JToggleButton viewpass;
    // End of variables declaration//GEN-END:variables

    private String customerpassconfirm;
private double checktempbalance;

    public Double getChecktempbalance() {
        return checktempbalance;
    }
   
    
    




}
