import java.awt.Cursor;
import java.util.concurrent.TimeUnit;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Speed
 */
public class CustomerAccountcreated extends javax.swing.JFrame {
boolean isclicked = false;
 
    /**
     * Creates new form AdeBankingDriver
     */
    public CustomerAccountcreated() {
 

        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaccountcreated = new javax.swing.JPanel();
        lblwelcome = new javax.swing.JLabel();
        iconprofileadded = new javax.swing.JLabel();
        lblexit = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblremember = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 153));
        setUndecorated(true);

        jpaccountcreated.setBackground(new java.awt.Color(0, 153, 204));
        jpaccountcreated.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblwelcome.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(255, 255, 255));
        String name = CustomerCreateaccount.Instance.customerfirst;
        lblwelcome.setText("Welcome, " + name);

        iconprofileadded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profileadd0.png"))); // NOI18N

        lblexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exiticon.png"))); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        lblid.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        lblid.setForeground(new java.awt.Color(255, 255, 255));
        String ID = CustomerCreateaccount.Instance.customerID;
        lblid.setText("Your Account ID is: " + ID);

        lblremember.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        lblremember.setForeground(new java.awt.Color(255, 255, 255));
        lblremember.setText("Remember your account ID for logging in!");

        javax.swing.GroupLayout jpaccountcreatedLayout = new javax.swing.GroupLayout(jpaccountcreated);
        jpaccountcreated.setLayout(jpaccountcreatedLayout);
        jpaccountcreatedLayout.setHorizontalGroup(
            jpaccountcreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                .addGroup(jpaccountcreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(iconprofileadded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(lblexit))
                    .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                        .addGroup(jpaccountcreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(lblwelcome))
                            .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblremember))
                            .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(lblid)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpaccountcreatedLayout.setVerticalGroup(
            jpaccountcreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                .addGroup(jpaccountcreatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(iconprofileadded))
                    .addGroup(jpaccountcreatedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblexit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblremember)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaccountcreated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaccountcreated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordField2ActionPerformed

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
 this.dispose();
      lblexit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));       
    }//GEN-LAST:event_lblexitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new CustomerAccountcreated().setVisible(true);
                

            }
            
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconprofileadded;
    private javax.swing.JPanel jpaccountcreated;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblremember;
    private javax.swing.JLabel lblwelcome;
    // End of variables declaration//GEN-END:variables




}
