
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.Random;

import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Speed
 */
public class CustomerCreateaccount extends javax.swing.JFrame {

   
    public static CustomerCreateaccount Instance;

    /**
     * Creates new form UserLogin
     */
    public CustomerCreateaccount() {

        initComponents();
        Instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconprofile = new javax.swing.JLabel();
        lbladminlog = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        lblexit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbladminlog1 = new javax.swing.JLabel();
        jtfFirstName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        jtfLastName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lblPPSN = new javax.swing.JLabel();
        jtfPPSN = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblDOB = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jpfPassword = new javax.swing.JPasswordField();
        lblpass = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        viewpass = new javax.swing.JToggleButton();
        jpfPassword1 = new javax.swing.JPasswordField();
        lblpass1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        viewpass1 = new javax.swing.JToggleButton();
        jdcDOB = new com.toedter.calendar.JDateChooser();
        lblerrormessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        iconprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N

        lbladminlog.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbladminlog.setForeground(new java.awt.Color(255, 255, 255));
        lbladminlog.setText("CREATE BANK ACCOUNT");

        btncreate.setBackground(new java.awt.Color(2, 94, 144));
        btncreate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(255, 255, 255));
        btncreate.setText("CREATE ACCOUNT");
        btncreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        lblexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exiticon.png"))); // NOI18N
        lblexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexitMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(2, 94, 144));

        lbladminlog1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbladminlog1.setForeground(new java.awt.Color(2, 94, 144));
        lbladminlog1.setText("PERSONAL INFORMATION");

        jtfFirstName.setBackground(new java.awt.Color(0, 153, 204));
        jtfFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfFirstName.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lblFirstName.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name:");

        jtfLastName.setBackground(new java.awt.Color(0, 153, 204));
        jtfLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfLastName.setBorder(null);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        lblPPSN.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblPPSN.setForeground(new java.awt.Color(255, 255, 255));
        lblPPSN.setText("PPSN:");

        jtfPPSN.setBackground(new java.awt.Color(0, 153, 204));
        jtfPPSN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtfPPSN.setBorder(null);

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        lblDOB.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblDOB.setText("Date Of Birth:");

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jpfPassword.setBackground(new java.awt.Color(0, 153, 204));
        jpfPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpfPassword.setBorder(null);
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });

        lblpass.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblpass.setForeground(new java.awt.Color(255, 255, 255));
        lblpass.setText("Password:");

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        viewpass.setBackground(new java.awt.Color(0, 153, 204));
        viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        viewpass.setSelected(true);
        viewpass.setBorder(null);
        viewpass.setBorderPainted(false);
        viewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpassActionPerformed(evt);
            }
        });

        jpfPassword1.setBackground(new java.awt.Color(0, 153, 204));
        jpfPassword1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jpfPassword1.setBorder(null);
        jpfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPassword1ActionPerformed(evt);
            }
        });

        lblpass1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblpass1.setForeground(new java.awt.Color(255, 255, 255));
        lblpass1.setText("Confirm Password:");

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        viewpass1.setBackground(new java.awt.Color(0, 153, 204));
        viewpass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png"))); // NOI18N
        viewpass1.setSelected(true);
        viewpass1.setBorder(null);
        viewpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpass1ActionPerformed(evt);
            }
        });

        jdcDOB.setBackground(new java.awt.Color(0, 153, 204));
        jdcDOB.setForeground(new java.awt.Color(0, 153, 204));
        jdcDOB.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblerrormessage.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblerrormessage.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastName)
                                    .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPPSN)
                                    .addComponent(jtfPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblpass)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(viewpass)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpass1)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jpfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(viewpass1))
                                    .addComponent(lblDOB)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jdcDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbladminlog1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lbladminlog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(iconprofile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblerrormessage)
                            .addComponent(btncreate))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblexit)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblexit)
                .addGap(12, 12, 12)
                .addComponent(iconprofile)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbladminlog)
                        .addGap(48, 48, 48)
                        .addComponent(lbladminlog1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(lblPPSN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblDOB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfPPSN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblpass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(viewpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblpass1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jpfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(viewpass1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jdcDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblerrormessage)
                .addGap(26, 26, 26)
                .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed

        String testpass;
        String testpass1;
   
        
       
        

        customerfirst = jtfFirstName.getText();
        customerlast = jtfLastName.getText();
        customerPPSN = jtfPPSN.getText();
        customerDOB = ((JTextField) jdcDOB.getDateEditor().getUiComponent()).getText();
        testpass = jpfPassword.getText();
        testpass1 = jpfPassword1.getText();

        if (customerfirst.equals("") || customerlast.equals("") || customerPPSN.equals("") || customerDOB.equals("")) {

            new ErrorFields().setVisible(true);

        } else if (!testpass.equals(testpass1)) {
            new ErrorPasswordmismatch().setVisible(true);
            jpfPassword.setText("");
            jpfPassword1.setText("");
        } else if (testpass.length() < 7 || (testpass1.length() < 7)) {
            new ErrorCustomerlength().setVisible(true);
            jpfPassword.setText("");
            jpfPassword1.setText("");
        }

        else if (customerPPSN.length() < 7 || (customerPPSN.length() < 7)) {
            new ErrorCustomerppsn().setVisible(true);
            jtfPPSN.setText("");

        } else {

        customerpass = testpass;
     
        Random rand = new Random();
        
        char CustomerIDletter1 = customerfirst.charAt(0);
        char CustomerIDletter2 = customerfirst.charAt(1);
        char CustomerIDletter3 = customerlast.charAt(1);
        char CustomerIDletter4 = customerlast.charAt(0);
        char CustomerIDletter5 = customerPPSN.charAt(3);
        char CustomerIDletter6 = customerPPSN.charAt(4);
        char CustomerIDletter7 = customerPPSN.charAt(3);
        char CustomerIDletter8 = customerDOB.charAt(0);
        char CustomerIDletter9 = customerDOB.charAt(9);
        
        accountnumber = "" + CustomerIDletter8 + "" + CustomerIDletter9 + rand.nextInt(10000);
        customerID = "" + CustomerIDletter1 + "" + CustomerIDletter2 + "" + CustomerIDletter3 + "" + CustomerIDletter4
                + "" + CustomerIDletter5 + "" + CustomerIDletter6 + "" + CustomerIDletter7 + "" + CustomerIDletter8
                + "" + CustomerIDletter9;
        double transamount= 0.00;
        Customer newcustomer = new Customer(customerfirst, customerlast, customerpass, customerID, customerPPSN, customerDOB,accountnumber);
        AccountTransactions newtransactions = new AccountTransactions (balance, accountnumber, dateoftransaction, typeoftransaction, transamount);
        
       AdeBank.Instance.getLbllogin().setEnabled(true);

        this.dispose();
        Customer.customers.add(newcustomer);
        AccountTransactions.transactions.add(newtransactions);
        new CustomerAccountcreated().setVisible(true);

        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void lblexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexitMouseClicked
        lblexit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.dispose();
    }//GEN-LAST:event_lblexitMouseClicked

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed

    }//GEN-LAST:event_jpfPasswordActionPerformed

    private void viewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpassActionPerformed
        if (viewpass.isSelected()) {

            jpfPassword.setEchoChar('*');
            viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png")));

        } else {

            jpfPassword.setEchoChar((char) 0);
            viewpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png")));

        }
    }//GEN-LAST:event_viewpassActionPerformed

    private void jpfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPassword1ActionPerformed

    private void viewpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpass1ActionPerformed
        if (viewpass1.isSelected()) {

            jpfPassword1.setEchoChar('*');
            viewpass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye_hide.png")));

        } else {

            jpfPassword1.setEchoChar((char) 0);
            viewpass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eye.png")));

        }
    }//GEN-LAST:event_viewpass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdeBankingDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new CustomerCreateaccount().setVisible(true);
            }
        });
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JLabel iconprofile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private com.toedter.calendar.JDateChooser jdcDOB;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfPassword1;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JTextField jtfPPSN;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPPSN;
    private javax.swing.JLabel lbladminlog;
    private javax.swing.JLabel lbladminlog1;
    private javax.swing.JLabel lblerrormessage;
    private javax.swing.JLabel lblexit;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JToggleButton viewpass;
    private javax.swing.JToggleButton viewpass1;
    // End of variables declaration//GEN-END:variables
 String customerfirst;
    String customerlast;
    String customerpass;
    String customerID;
    String customerPPSN;
    String customerDOB;
    String accoutnumber;
    double balance = 0.00;
    String accountnumber;
    String dateoftransaction = ".";
    String typeoftransaction =".";
    


}
